#!/usr/bin/env bash

print_usage () {
  cat <<EOF

Usage:

haida build
  Build the project
haida unit [test]
  Run unit test [test] or run all unit tests if no test supplied
haida perf run [unit] [-i]
  Run performance testing on code unit [unit] and store the results in a file
  Provide no [unit] to get a list of units
  -i: supply custom testing parameters interactively
haida perf plot <file>
  Plot the results of performance testing stored in <file>
  <file> should not include the path or extension
EOF
}

case "$1" in
  build) (cd src\\nn\\operations; python setup.py install);;
  unit)
    if [ -z "$2" ]
    then
      python -m unittest discover -s test/unit -v
    else
      python -m unittest "$2" -v
    fi;;
  perf)
    python -m test.perf "${@:2}"
    if [ $? -eq 2 ]; then
      print_usage
    fi;;
  *) print_usage;;
esac
